/**
 * Deploy supergraph to DDN Cloud.
 *
 * Fetches secrets from AWS SSM, generates a temporary .env.cloud file,
 * builds connectors + supergraph, applies, then cleans up.
 *
 * The DDN CLI builds connectors first, auto-populates their URLs in
 * .env.cloud, then submits the supergraph build to DDN Cloud.
 *
 * Usage:
 *   AWS_PROFILE=banyan bun run hasura:deploy
 */

import { fetchSSMParams, requireParam } from "../lib/ssm.ts";

const DDN = `${process.env.HOME}/.local/bin/ddn`;
const DDN_DIR = new URL("../ddn", import.meta.url).pathname;
const ENV_CLOUD_PATH = `${DDN_DIR}/.env.cloud`;

// Fetch secrets from SSM
console.log("Fetching secrets from SSM...");
const params = await fetchSSMParams();

const connectionUri = requireParam(params, "ddn-connection-uri");
const jwtSecretKey = requireParam(params, "jwt-secret-key");

// Connector config vars. READ_URL/WRITE_URL/AUTHORIZATION_HEADER are
// auto-populated by DDN CLI from connector builds into .env.cloud.
const envContent = [
  `APP_BANYAN_PG_CONNECTION_URI="${connectionUri}"`,
  `JWT_SECRET_KEY="${jwtSecretKey}"`,
  "",
].join("\n");

// Clean up .env.cloud on any exit
const cleanup = () => {
  Bun.write(ENV_CLOUD_PATH, "# Generated by deploy script — do not edit manually\n");
  console.log("\nCleaned up env files.");
};

process.on("SIGINT", () => { cleanup(); process.exit(130); });
process.on("SIGTERM", () => { cleanup(); process.exit(143); });

let exitCode = 1;
try {
  await Bun.write(ENV_CLOUD_PATH, envContent);
  console.log("Generated .env.cloud from SSM parameters.");

  // Build connectors + supergraph on DDN Cloud
  console.log("Building supergraph on DDN Cloud...\n");

  // Pass JWT_SECRET_KEY via process env so it survives DDN CLI
  // overwriting .env.cloud during connector builds.
  const buildProc = Bun.spawn(
    [DDN, "supergraph", "build", "create", "--out", "json", "--timeout", "900"],
    {
      cwd: DDN_DIR,
      stdout: "pipe",
      stderr: "inherit",
      env: { ...process.env, JWT_SECRET_KEY: jwtSecretKey, PATH: `${process.env.HOME}/.local/bin:${process.env.PATH}` },
    },
  );

  const buildOutput = await new Response(buildProc.stdout).text();
  const buildExitCode = await buildProc.exited;

  if (buildExitCode !== 0) {
    console.error("Build failed.");
    exitCode = buildExitCode;
  } else {
    const buildResult = JSON.parse(buildOutput);
    const buildVersion = buildResult.build_version;
    console.log(`Build version: ${buildVersion}`);

    // Apply the build
    console.log("Applying supergraph build...\n");

    const applyProc = Bun.spawn(
      [DDN, "supergraph", "build", "apply", buildVersion],
      {
        cwd: DDN_DIR,
        stdio: ["inherit", "inherit", "inherit"],
        env: { ...process.env, PATH: `${process.env.HOME}/.local/bin:${process.env.PATH}` },
      },
    );

    exitCode = await applyProc.exited;
  }
} finally {
  cleanup();
}

process.exit(exitCode);
