/**
 * Deploy supergraph to DDN Cloud.
 *
 * Fetches secrets from AWS SSM, generates a temporary .env.cloud file,
 * runs `ddn supergraph build create --apply`, then cleans up.
 *
 * Usage:
 *   AWS_PROFILE=banyan bun run hasura:deploy
 */

import { fetchSSMParams, requireParam } from "../lib/ssm.ts";

const DDN_DIR = new URL("../ddn", import.meta.url).pathname;
const ENV_CLOUD_PATH = `${DDN_DIR}/.env.cloud`;

// Fetch secrets from SSM
console.log("Fetching secrets from SSM...");
const params = await fetchSSMParams();

const connectionUri = requireParam(params, "ddn-connection-uri");
const jwtSecretKey = requireParam(params, "jwt-secret-key");

// Generate .env.cloud from SSM values
const envContent = [
  `APP_BANYAN_PG_CONNECTION_URI="${connectionUri}"`,
  `JWT_SECRET_KEY="${jwtSecretKey}"`,
  "",
].join("\n");

await Bun.write(ENV_CLOUD_PATH, envContent);
console.log("Generated .env.cloud from SSM parameters.");

// Run ddn supergraph build create --apply
console.log("Building and deploying supergraph to DDN Cloud...\n");

const proc = Bun.spawn(
  ["ddn", "supergraph", "build", "create", "--apply"],
  {
    cwd: DDN_DIR,
    stdio: ["inherit", "inherit", "inherit"],
    env: { ...process.env, PATH: `${process.env.HOME}/.local/bin:${process.env.PATH}` },
  },
);

const exitCode = await proc.exited;

// Clean up .env.cloud
await Bun.write(ENV_CLOUD_PATH, "# Generated by deploy script — do not edit manually\n");
console.log("\nCleaned up .env.cloud.");

process.exit(exitCode);
