/**
 * Generate local .env file for DDN development from AWS SSM.
 *
 * Fetches secrets from SSM Parameter Store and writes hasura/ddn/.env
 * with the correct values for local development (connector on localhost,
 * DB via SSM tunnel on port 15432).
 *
 * Usage:
 *   AWS_PROFILE=banyan bun run hasura:setup
 */

import { fetchSSMParams, requireParam } from "../lib/ssm.ts";

const DDN_DIR = new URL("../ddn", import.meta.url).pathname;
const ENV_PATH = `${DDN_DIR}/.env`;

console.log("Fetching secrets from SSM...");
const params = await fetchSSMParams();

const dbConnectionUri = requireParam(params, "db-connection-uri");
const jwtSecretKey = requireParam(params, "jwt-secret-key");
const appleEndpoint = params.get("apple-endpoint") ?? "https://prod.apple.papaya.services/v1/graphql";
const appleAdminSecret = requireParam(params, "apple-admin-secret");

// Rewrite DB host to localhost tunnel
const tunnelUri = dbConnectionUri.replace(
  /(@)[^:]+(:5432)/,
  "$1localhost:15432",
);

// Generate a random service token for local connector auth
const tokenBytes = crypto.getRandomValues(new Uint8Array(24));
const serviceToken = btoa(String.fromCharCode(...tokenBytes));

// Doltgres connection URI — rewrite NLB endpoint to local tunnel
// DDN CLI requires local.hasura.dev instead of localhost
const doltgresDdnUri = requireParam(params, "doltgres-ddn-connection-uri");
const doltgresTunnelUri = doltgresDdnUri.replace(
  /(@)[^:]+(:5433)/,
  "$1local.hasura.dev:25432",
);

const envContent = `# Generated by setup-env.ts — do not edit manually
# Re-run: AWS_PROFILE=banyan bun run hasura:setup
APP_BANYAN_PG_AUTHORIZATION_HEADER="Bearer ${serviceToken}"
APP_BANYAN_PG_CONNECTION_URI="${tunnelUri}"
APP_BANYAN_PG_HASURA_CONNECTOR_PORT=7892
APP_BANYAN_PG_HASURA_SERVICE_TOKEN_SECRET="${serviceToken}"
APP_BANYAN_PG_OTEL_EXPORTER_OTLP_ENDPOINT="http://local.hasura.dev:4317"
APP_BANYAN_PG_OTEL_SERVICE_NAME="app_banyan_pg"
APP_BANYAN_PG_READ_URL="http://local.hasura.dev:7892"
APP_BANYAN_PG_WRITE_URL="http://local.hasura.dev:7892"
APP_BANYAN_DOLTGRES_AUTHORIZATION_HEADER="Bearer ${serviceToken}"
APP_BANYAN_DOLTGRES_CONNECTION_URI="${doltgresTunnelUri}"
APP_BANYAN_DOLTGRES_HASURA_CONNECTOR_PORT=7893
APP_BANYAN_DOLTGRES_HASURA_SERVICE_TOKEN_SECRET="${serviceToken}"
APP_BANYAN_DOLTGRES_OTEL_EXPORTER_OTLP_ENDPOINT="http://local.hasura.dev:4317"
APP_BANYAN_DOLTGRES_OTEL_SERVICE_NAME="app_banyan_doltgres"
APP_BANYAN_DOLTGRES_READ_URL="http://local.hasura.dev:7893"
APP_BANYAN_DOLTGRES_WRITE_URL="http://local.hasura.dev:7893"
JWT_SECRET_KEY="${jwtSecretKey}"
APPLE_APPLE_GQL_GRAPHQL_ENDPOINT="${appleEndpoint}"
APPLE_APPLE_GQL_GRAPHQL_ENDPOINT_1="${appleEndpoint}"
APPLE_APPLE_GQL_ADMIN_SECRET="${appleAdminSecret}"
APPLE_APPLE_GQL_AUTHORIZATION_HEADER="Bearer ${serviceToken}"
APPLE_APPLE_GQL_HASURA_CONNECTOR_PORT_1=7893
APPLE_APPLE_GQL_HASURA_SERVICE_TOKEN_SECRET_1="${serviceToken}"
APPLE_APPLE_GQL_OTEL_EXPORTER_OTLP_ENDPOINT_1="http://local.hasura.dev:4317"
APPLE_APPLE_GQL_OTEL_SERVICE_NAME_1="apple_apple_gql"
APPLE_APPLE_GQL_READ_URL="http://local.hasura.dev:7893"
APPLE_APPLE_GQL_WRITE_URL="http://local.hasura.dev:7893"
`;

await Bun.write(ENV_PATH, envContent);
console.log(`Written ${ENV_PATH}`);
console.log("\nLocal .env ready. Start the tunnel first:");
console.log("  AWS_PROFILE=banyan bun run hasura:tunnel");
