/**
 * Generate local .env file for DDN development from AWS SSM.
 *
 * Fetches secrets from SSM Parameter Store and writes hasura/ddn/.env
 * with the correct values for local development (connector on localhost,
 * DB via SSM tunnel on port 15432).
 *
 * Usage:
 *   AWS_PROFILE=banyan bun run hasura:setup
 */

import { fetchSSMParams, requireParam } from "../lib/ssm.ts";

const DDN_DIR = new URL("../ddn", import.meta.url).pathname;
const ENV_PATH = `${DDN_DIR}/.env`;

console.log("Fetching secrets from SSM...");
const params = await fetchSSMParams();

const dbConnectionUri = requireParam(params, "db-connection-uri");
const jwtSecretKey = requireParam(params, "jwt-secret-key");
const phoenixAuthServiceUrl = params["phoenix-auth-service-url"] ?? "https://oasis.papaya.asia";

// Rewrite DB host to localhost tunnel
const tunnelUri = dbConnectionUri.replace(
  /(@)[^:]+(:5432)/,
  "$1localhost:15432",
);

// Generate a random service token for local connector auth
const tokenBytes = crypto.getRandomValues(new Uint8Array(24));
const serviceToken = btoa(String.fromCharCode(...tokenBytes));

const envContent = `# Generated by setup-env.ts — do not edit manually
# Re-run: AWS_PROFILE=banyan bun run hasura:setup
APP_BANYAN_PG_AUTHORIZATION_HEADER="Bearer ${serviceToken}"
APP_BANYAN_PG_CONNECTION_URI="${tunnelUri}"
APP_BANYAN_PG_HASURA_CONNECTOR_PORT=7892
APP_BANYAN_PG_HASURA_SERVICE_TOKEN_SECRET="${serviceToken}"
APP_BANYAN_PG_OTEL_EXPORTER_OTLP_ENDPOINT="http://local.hasura.dev:4317"
APP_BANYAN_PG_OTEL_SERVICE_NAME="app_banyan_pg"
APP_BANYAN_PG_READ_URL="http://local.hasura.dev:7892"
APP_BANYAN_PG_WRITE_URL="http://local.hasura.dev:7892"
APP_PHOENIX_TS_AUTH_SERVICE_URL="${phoenixAuthServiceUrl}"
APP_PHOENIX_TS_AUTHORIZATION_HEADER="Bearer ${serviceToken}"
APP_PHOENIX_TS_HASURA_CONNECTOR_PORT=5793
APP_PHOENIX_TS_HASURA_SERVICE_TOKEN_SECRET="${serviceToken}"
APP_PHOENIX_TS_OTEL_EXPORTER_OTLP_ENDPOINT="http://local.hasura.dev:4317"
APP_PHOENIX_TS_OTEL_SERVICE_NAME="app_phoenix_ts"
APP_PHOENIX_TS_READ_URL="http://local.hasura.dev:5793"
APP_PHOENIX_TS_WRITE_URL="http://local.hasura.dev:5793"
JWT_SECRET_KEY="${jwtSecretKey}"
`;

await Bun.write(ENV_PATH, envContent);
console.log(`Written ${ENV_PATH}`);
console.log("\nLocal .env ready. Start the tunnel first:");
console.log("  AWS_PROFILE=banyan bun run hasura:tunnel");
