services:
  apple_apple_gql:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.apple_gql
    environment:
      GRAPHQL_ENDPOINT: $APPLE_APPLE_GQL_GRAPHQL_ENDPOINT_1
      GRAPHQL_ADMIN_SECRET: $APPLE_APPLE_GQL_ADMIN_SECRET
      HASURA_SERVICE_TOKEN_SECRET: $APPLE_APPLE_GQL_HASURA_SERVICE_TOKEN_SECRET_1
      OTEL_EXPORTER_OTLP_ENDPOINT: $APPLE_APPLE_GQL_OTEL_EXPORTER_OTLP_ENDPOINT_1
      OTEL_SERVICE_NAME: $APPLE_APPLE_GQL_OTEL_SERVICE_NAME_1
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 8943:8080
